### ISSUE TITLE
Needs a README, instructions for how to setup

### ISSUE THREAD

**Issue by jaburns** [libsm64/libsm64-unity#1]

**Comment by HUBE07** [comment]
Hey... Just wondering... How's the README going? And... I know you are very ocupied, sorry. I hope you have a great day, evening, night, or time you are seeing this.

**Comment by jaburns** [comment]
Sorry, busy week. I'll be getting to it in the next few hours though.

**Comment by HUBE07** [comment]
Ok, don't worry, I get that, I was just curious. Thx for responding 😄

**Comment by jaburns** [comment]
Got a simple readme up. It mainly just redirects to here where the real instructions are https://github.com/libsm64/libsm64-unity-dev . I'll close this issue, and if you have any problems getting that Unity project running feel free to open an issue there.

**Comment by HUBE07** [comment]
Ok, THX A LOT (Sorry for not answering i got sleepy)
