### ISSUE TITLE
Update to the latest version of libsm64

### ISSUE THREAD

**Issue by benjaminpants** [libsm64/libsm64-unity#2]
This is really cool. Though a proper update to the latest version of the dll would be nice. I tried doing it myself via using the blender libsm64 dll, and after changing surfaces from shorts to ints the game didn't crash however mario just kind of instantly disappeared (along with the near magnitude 0 error). So if an official update to this ported it to latest lib version that'd be really appreciated.

The main use of upgrading the lib version is 32 bit collisions instead of 16 bit ones.

**Comment by jaburns** [comment]
Good point, will do.

**Comment by jaburns** [comment]
Done
