### ISSUE TITLE
Setup for ingame usage

### ISSUE THREAD

**Issue by KidoHyde** [libsm64/libsm64-unity#3]
Me and a friend have been trying to set this up for general usage in unity games just for the sake of it, while it still works in unity in-game it seems to have the following issue where the model doesn't show up and the log returns null marios, 

At the moment I have the scripts all in a dll that I load on game boot up (along with the rom and sm64.dll), and on level load I 
[code]
var Z = UnityEngine.Object.FindObjectOfType<SmoothCamera>();
                    
                    var A = LoadedPlayers.LoadAsset<GameObject>("mario");
                    A.GetComponent<ExampleInputProvider>().cameraObject = Z.gameObject;
                    _CustomModel = GameObject.Instantiate(A, __instance.transform.position, Quaternion.identity);
                    [/code]
                    (neither are null)
 I did see [here ](https://github.com/libsm64/libsm64-unity/issues/2)that another user was having similar issues, if it's just a case of updating I can wait as long as you need (and would be sorry to waste your time with this post), thanks in advance!

**Comment by KidoHyde** [comment]
Will test then! Thanks a ton!

**Comment by jaburns** [comment]
Sorry, lost track of this. Will do soon

**Comment by jaburns** [comment]
@KidoHyde The libsm64 binaries are updated to the latest versions now, hopefully that fixes your issue.

**Comment by jaburns** [comment]
Assuming this is solved. If not, feel free to re-open.

**Comment by KidoHyde** [comment]
Ah yeah sorry yes this was fixed, the issue wasn't with the dll itself but the lack of the terrein 
actors in the world as one is required for it to work (for any future onlookers)
