### ISSUE TITLE
Update to Unity 2020 LTS and make this an ACTUAL unitypackage file

### ISSUE THREAD

**Issue by Bloxxel64** [libsm64/libsm64-unity#6]
So I tried to use this in a Baldi's Basics project. but there was no unitypackage file, so I copy and pasted all the files. and it broke. Please add proper support.

**Comment by jaburns** [comment]
Pull requests are welcome

**Comment by jaburns** [comment]
This isn't intended to be a unitypackage, it's intended to be used through the package manager as stated in the readme. To import it, point the unity package manager to this git repo and it should import fine.
