### ISSUE TITLE
Audio support?

### ISSUE THREAD

**Issue by hatoving** [libsm64/libsm64-unity#7]
Heyo, I just wanted to say that I'm absolutely enjoying messing around with Mario in Unity. 
The possibilities are probably endless if you think about it. 

There's just one thing that bugs me a bit: Would it be possible to add audio support and a little more features to Mario (as in, custom color support, ability to grab and hold stuff, the particles such as the stars, water support, etc.)?

I'm not entirely familiar on how the entire library works and how it's implemented in Unity, so sorry if my question seems like the most stupidest thing anyone's witnessed lol.

Thanks for reading,
-hat

**Comment by jaburns** [comment]
Audio support would be really good actually. There's an open issue in libsm64 to add water boxes. I'll open a ticket in the libsm64 repo for audio. I'm personally not really working on the Unity plugin, but I'm happy to accept PRs. When I get less busy with other stuff I do intend to add some more stuff like audio and water to libsm64 itself though, so Unity integration of those features should be easy at that point.
